import { createServer } from 'node:http';
import { randomBytes, randomInt, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { Server } from 'socket.io';
import { getBoardPreset } from '../src/boardPresets.js';
import { createSettings } from '../src/gameConfig.js';

// Render and most Node hosts assign PORT. MULTIPLAYER_PORT remains available
// for the existing local Windows scripts.
const PORT = Number(process.env.PORT || process.env.MULTIPLAYER_PORT || 3001);
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN || '*';
const ROOM_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const COLORS = ['#ea5b3d','#3c73df','#23a476','#9a62d5','#eba928','#e35f96','#168ea1','#73564a'];
const MODES = new Set(['classic','fate','party','custom']);
const BOARDS = new Set(['classic','climbers','snake-pit','wheel-mania','chaos-realm']);
const ROLL_TIMEOUT_MS = 30_000;
const rooms = new Map();
const attempts = new Map();

const cleanText = (value, max = 18) => String(value || '').replace(/[<>\x00-\x1f]/g, '').trim().slice(0, max);
const cleanCode = value => String(value || '').toUpperCase().replace(/[^A-HJ-NP-Z2-9]/g, '').slice(0, 6);
const token = () => randomBytes(24).toString('base64url');
function roomCode() { for (let tries = 0; tries < 50; tries++) { let code = ''; for (let i = 0; i < 6; i++) code += ROOM_ALPHABET[randomInt(ROOM_ALPHABET.length)]; if (!rooms.has(code)) return code; } throw new Error('Unable to allocate room code'); }
function limited(socket, action, limit = 8, windowMs = 10000) { const key = `${socket.handshake.address}:${action}`, now = Date.now(), recent = (attempts.get(key) || []).filter(time => now - time < windowMs); recent.push(now); attempts.set(key, recent); return recent.length > limit; }
function publicRoom(room) { return { code: room.code, status: room.status, phase: room.phase, actionDeadline: room.actionDeadline || null, hostId: room.hostId, settings: room.settings, boardPresetId: room.boardPresetId, eventSequence: room.eventSequence, currentPlayerIndex: room.currentPlayerIndex, round: room.round, winnerId: room.winnerId, log: room.log || [], players: room.players.map(({ sessionToken, socketId, ...player }) => player) }; }
function broadcast(room, event = 'room:update') { room.updatedAt = Date.now(); room.eventSequence++; room.io.to(room.code).emit(event, publicRoom(room)); }
function gameEvent(room, type, payload) { room.eventSequence++; return { sequence: room.eventSequence, type, payload }; }
function gameLog(room, text) { room.log.unshift({ text, sequence: room.eventSequence }); room.log = room.log.slice(0, 10); }
function initializeGame(room) { const settings = createSettings(room.settings.mode, room.settings), board = getBoardPreset(room.boardPresetId); room.settings = settings; room.boardPresetId = board.id; room.currentPlayerIndex = 0; room.round = 1; room.winnerId = null; room.phase = 'WAITING_FOR_ROLL'; room.log = []; room.players.forEach(player => { player.position = 0; player.inventory = []; player.statusEffects = { skipNextTurn: false, diceCurse: false }; player.stats = { diceRolls: 0, diceTotal: 0, totalSpacesMoved: 0, snakesHit: 0, laddersClimbed: 0 }; }); gameLog(room, `${room.players[0].name} begins the race.`); }
function resolveCoreRoll(room, player) {
  const events = [], board = getBoardPreset(room.boardPresetId), roll = randomInt(1, 7), from = player.position, destination = from + roll;
  player.stats.diceRolls++; player.stats.diceTotal += roll; events.push(gameEvent(room, 'DICE_ROLLED', { playerId: player.id, result: roll })); gameLog(room, `${player.name} rolled ${roll}.`);
  if (room.settings.exactRoll && destination > 100) { events.push(gameEvent(room, 'MOVE_BLOCKED', { playerId: player.id, from, roll })); gameLog(room, `${player.name} needs an exact roll to reach 100.`); }
  else { const to = Math.min(100, destination), path = Array.from({ length: to - from }, (_, index) => from + index + 1); player.position = to; player.stats.totalSpacesMoved += path.length; events.push(gameEvent(room, 'PLAYER_MOVED', { playerId: player.id, from, to, path })); gameLog(room, `${player.name} moved to Tile ${to}.`); let guard = 0; while (guard++ < 10) { const snakeTo = board.snakes[player.position], ladderTo = board.ladders[player.position]; if (!snakeTo && !ladderTo) break; const kind = snakeTo ? 'SNAKE_TRIGGERED' : 'LADDER_TRIGGERED', eventFrom = player.position, eventTo = snakeTo || ladderTo; player.position = eventTo; if (snakeTo) player.stats.snakesHit++; else player.stats.laddersClimbed++; events.push(gameEvent(room, kind, { playerId: player.id, from: eventFrom, to: eventTo })); gameLog(room, `${player.name} ${snakeTo ? 'slid down a snake' : 'climbed a ladder'} to ${eventTo}.`); } }
  if (player.position === 100) { room.winnerId = player.id; room.status = 'finished'; room.phase = 'GAME_OVER'; events.push(gameEvent(room, 'GAME_WON', { playerId: player.id })); gameLog(room, `${player.name} won the match!`); }
  else { const extraTurn = roll === 6 && room.settings.extraTurnOnSix; if (!extraTurn) { room.currentPlayerIndex = (room.currentPlayerIndex + 1) % room.players.length; if (room.currentPlayerIndex === 0) room.round++; } room.phase = extraTurn ? 'WAITING_FOR_EXTRA_TURN_CONFIRMATION' : 'WAITING_FOR_ROLL'; events.push(gameEvent(room, 'TURN_CHANGED', { playerId: room.players[room.currentPlayerIndex].id, round: room.round, extraTurn })); if (extraTurn) gameLog(room, `${player.name} rolled a six and earned an extra turn.`); }
  return events;
}
function clearRollTimer(room) { if (room.rollTimer) clearTimeout(room.rollTimer); room.rollTimer = null; room.actionDeadline = null; }
function scheduleRollTimer(room) {
  clearRollTimer(room);
  if (room.status !== 'playing' || room.phase !== 'WAITING_FOR_ROLL') return;
  room.actionDeadline = Date.now() + ROLL_TIMEOUT_MS;
  room.rollTimer = setTimeout(() => { if (room.status !== 'playing' || room.phase !== 'WAITING_FOR_ROLL') return; const player = room.players[room.currentPlayerIndex]; room.phase = 'RESOLVING_TURN'; room.actionDeadline = null; const events = resolveCoreRoll(room, player); gameLog(room, `${player.name} ran out of time, so the server rolled automatically.`); scheduleRollTimer(room); room.updatedAt = Date.now(); room.io.to(room.code).emit('game:events', { events, snapshot: publicRoom(room) }); }, ROLL_TIMEOUT_MS);
  room.rollTimer.unref?.();
}
function findPlayer(room, socket) { return room?.players.find(player => player.socketId === socket.id); }
function chooseColor(room, requested) { const used = new Set(room.players.map(player => player.color)); return COLORS.includes(requested) && !used.has(requested) ? requested : COLORS.find(color => !used.has(color)); }
function validIdentity(data) { const name = cleanText(data?.name), icon = cleanText(data?.icon, 4); return name.length >= 1 && icon.length >= 1 ? { name, icon } : null; }
function joinSocket(socket, room, player) { player.socketId = socket.id; player.connected = true; player.lastConnectedAt = Date.now(); socket.join(room.code); socket.data.roomCode = room.code; socket.data.playerId = player.id; }

const serverDirectory = dirname(fileURLToPath(import.meta.url));
const builtGamePath = join(serverDirectory, '..', 'dist', 'index.html');
const httpServer = createServer((request, response) => {
  if (request.url === '/health') { response.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' }); response.end(JSON.stringify({ service: 'snake-ladder-multiplayer', status: 'ok', rooms: rooms.size })); return; }
  readFile(builtGamePath, (error, content) => { if (error) { response.writeHead(503, { 'content-type': 'text/plain' }); response.end('Game build unavailable. Run npm run build first.'); return; } response.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-cache' }); response.end(content); });
});
const io = new Server(httpServer, { cors: { origin: CLIENT_ORIGIN === '*' ? true : CLIENT_ORIGIN.split(','), methods: ['GET','POST'] }, maxHttpBufferSize: 16_384, pingTimeout: 20_000 });

io.on('connection', socket => {
  socket.on('room:create', (data, ack = () => {}) => { if (limited(socket, 'create', 4)) return ack({ ok: false, error: 'Too many attempts. Please wait.' }); const identity = validIdentity(data); if (!identity) return ack({ ok: false, error: 'Enter a valid name and icon.' }); const code = roomCode(), id = randomUUID(), sessionToken = token(); const room = { code, io, status: 'lobby', hostId: id, settings: { mode: 'fate', exactRoll: true, extraTurnOnSix: true, animationSpeed: 'normal' }, boardPresetId: 'classic', eventSequence: 0, createdAt: Date.now(), updatedAt: Date.now(), players: [] }; const player = { id, playerNumber: 1, sessionToken, ...identity, color: chooseColor(room, data.color), ready: true, connected: true, joinedAt: Date.now() }; room.players.push(player); rooms.set(code, room); joinSocket(socket, room, player); ack({ ok: true, sessionToken, playerId: id, room: publicRoom(room) }); broadcast(room); });
  socket.on('room:join', (data, ack = () => {}) => { if (limited(socket, 'join', 8)) return ack({ ok: false, error: 'Too many attempts. Please wait.' }); const code = cleanCode(data?.code), room = rooms.get(code), identity = validIdentity(data); if (!room) return ack({ ok: false, error: 'Room not found.' }); if (room.status !== 'lobby') return ack({ ok: false, error: 'Game already started.' }); if (room.players.length >= 8) return ack({ ok: false, error: 'Room is full.' }); if (!identity) return ack({ ok: false, error: 'Enter a valid name and icon.' }); if (room.players.some(player => player.name.toLowerCase() === identity.name.toLowerCase())) return ack({ ok: false, error: 'That name is already used.' }); const color = chooseColor(room, data.color); if (!color) return ack({ ok: false, error: 'No player colors remain.' }); const usedNumbers = new Set(room.players.map(player => player.playerNumber)); const playerNumber = Array.from({ length: 8 }, (_, index) => index + 1).find(number => !usedNumbers.has(number)); const player = { id: randomUUID(), playerNumber, sessionToken: token(), ...identity, color, ready: false, connected: true, joinedAt: Date.now() }; room.players.push(player); joinSocket(socket, room, player); ack({ ok: true, sessionToken: player.sessionToken, playerId: player.id, colorChanged: color !== data.color, room: publicRoom(room) }); broadcast(room); });
  socket.on('room:reconnect', (data, ack = () => {}) => { const room = rooms.get(cleanCode(data?.code)), player = room?.players.find(item => item.id === data?.playerId && item.sessionToken === data?.sessionToken); if (!room || !player) return ack({ ok: false, error: 'Reconnect session expired.' }); joinSocket(socket, room, player); ack({ ok: true, room: publicRoom(room) }); broadcast(room); });
  socket.on('room:ready', (data, ack = () => {}) => { const room = rooms.get(socket.data.roomCode), player = findPlayer(room, socket); if (!room || !player || room.status !== 'lobby' || player.id === room.hostId) return ack({ ok: false, error: 'Ready change rejected.' }); player.ready = Boolean(data?.ready); broadcast(room); ack({ ok: true }); });
  socket.on('room:settings', (data, ack = () => {}) => { const room = rooms.get(socket.data.roomCode), player = findPlayer(room, socket); if (!room || !player || player.id !== room.hostId || room.status !== 'lobby') return ack({ ok: false, error: 'Only the host can change settings.' }); const mode = MODES.has(data?.mode) ? data.mode : room.settings.mode, boardPresetId = BOARDS.has(data?.boardPresetId) ? data.boardPresetId : room.boardPresetId, animationSpeed = ['fast','normal','cinematic'].includes(data?.animationSpeed) ? data.animationSpeed : room.settings.animationSpeed; room.settings = { mode, exactRoll: Boolean(data?.exactRoll), extraTurnOnSix: Boolean(data?.extraTurnOnSix), animationSpeed }; room.boardPresetId = boardPresetId; broadcast(room); ack({ ok: true }); });
  socket.on('room:start', (_, ack = () => {}) => { const room = rooms.get(socket.data.roomCode), player = findPlayer(room, socket); if (!room || !player || player.id !== room.hostId || room.status !== 'lobby') return ack({ ok: false, error: 'Start rejected.' }); if (room.players.length < 2) return ack({ ok: false, error: 'At least 2 players are required.' }); if (room.players.some(item => item.id !== room.hostId && !item.ready)) return ack({ ok: false, error: 'Every player must be ready.' }); room.status = 'playing'; initializeGame(room); scheduleRollTimer(room); broadcast(room, 'game:started'); ack({ ok: true }); });
  socket.on('game:roll', (_, ack = () => {}) => { if (limited(socket, 'roll', 6, 3000)) return ack({ ok: false, error: 'Roll request rate limited.' }); const room = rooms.get(socket.data.roomCode), player = findPlayer(room, socket); if (!room || !player || room.status !== 'playing' || room.phase !== 'WAITING_FOR_ROLL') return ack({ ok: false, error: 'The match is not waiting for a roll.' }); if (room.players[room.currentPlayerIndex]?.id !== player.id) return ack({ ok: false, error: 'It is not your turn.' }); clearRollTimer(room); room.phase = 'RESOLVING_TURN'; const events = resolveCoreRoll(room, player); scheduleRollTimer(room); room.updatedAt = Date.now(); io.to(room.code).emit('game:events', { events, snapshot: publicRoom(room) }); ack({ ok: true, acceptedSequence: events[0]?.sequence }); });
  socket.on('game:confirm-extra-turn', (_, ack = () => {}) => { const room = rooms.get(socket.data.roomCode), player = findPlayer(room, socket); if (!room || !player || room.status !== 'playing' || room.phase !== 'WAITING_FOR_EXTRA_TURN_CONFIRMATION') return ack({ ok: false, error: 'No extra turn confirmation is pending.' }); if (room.players[room.currentPlayerIndex]?.id !== player.id) return ack({ ok: false, error: 'Only the active player can confirm.' }); room.phase = 'WAITING_FOR_ROLL'; scheduleRollTimer(room); room.eventSequence++; room.updatedAt = Date.now(); io.to(room.code).emit('game:extra-turn-confirmed', { playerId: player.id, snapshot: publicRoom(room) }); ack({ ok: true }); });
  socket.on('room:leave', (_, ack = () => {}) => { const room = rooms.get(socket.data.roomCode), player = findPlayer(room, socket); if (!room || !player) return ack({ ok: true }); room.players = room.players.filter(item => item.id !== player.id); socket.leave(room.code); if (!room.players.length) { clearRollTimer(room); rooms.delete(room.code); } else { if (room.hostId === player.id) room.hostId = [...room.players].sort((a,b) => a.joinedAt - b.joinedAt)[0].id; broadcast(room); } ack({ ok: true }); });
  socket.on('disconnect', () => { const room = rooms.get(socket.data.roomCode), player = room?.players.find(item => item.id === socket.data.playerId); if (!room || !player) return; player.connected = false; player.disconnectedAt = Date.now(); broadcast(room); });
});

setInterval(() => { const now = Date.now(); for (const [code, room] of rooms) if (now - room.updatedAt > 30 * 60_000 && room.players.every(player => !player.connected)) rooms.delete(code); for (const [key, times] of attempts) if (!times.some(time => now - time < 60_000)) attempts.delete(key); }, 60_000).unref();
httpServer.listen(PORT, '0.0.0.0', () => console.log(`Multiplayer server listening on http://0.0.0.0:${PORT}`));
