import { useEffect, useMemo, useState } from 'react';
import { BOARD_PRESETS } from '../boardPresets.js';
import { MODE_PRESETS, TOKEN_ICONS } from '../gameConfig.js';
import { createMultiplayerClient, MULTIPLAYER_SERVER_URL } from '../multiplayerClient.js';
import OnlineGame from './OnlineGame.jsx';
const COLORS = ['#ea5b3d','#3c73df','#23a476','#9a62d5','#eba928','#e35f96','#168ea1','#73564a'];
const call = (socket, event, payload) => new Promise(resolve => {
  if (!socket.connected) return resolve({ ok: false, error: 'Not connected to the multiplayer server. Check that port 3001 is available.' });
  socket.timeout(8000).emit(event, payload, (error, response) => resolve(error ? { ok: false, error: 'The multiplayer server did not respond. Please try again.' } : response));
});
export default function OnlineLobby({ onBack }) {
  const socket = useMemo(() => createMultiplayerClient(), []), [view,setView]=useState('menu'), [room,setRoom]=useState(null), [identity,setIdentity]=useState({name:'',icon:TOKEN_ICONS[0],color:COLORS[0]}), [code,setCode]=useState(''), [self,setSelf]=useState(null), [error,setError]=useState(''), [notice,setNotice]=useState(''), [pending,setPending]=useState(false), [connection,setConnection]=useState(socket.connected?'connected':'connecting');
  useEffect(()=>{const connected=()=>{setConnection('connected');setError('')},disconnected=()=>setConnection('reconnecting'),failed=error=>{setConnection('unavailable');setError(`Cannot reach ${MULTIPLAYER_SERVER_URL}: ${error.message}`)},update=next=>setRoom(next),started=next=>{setRoom(next);setView('game')};socket.on('connect',connected);socket.on('disconnect',disconnected);socket.on('connect_error',failed);socket.on('room:update',update);socket.on('game:started',started);socket.connect();return()=>{socket.off('connect',connected);socket.off('disconnect',disconnected);socket.off('connect_error',failed);socket.off('room:update',update);socket.off('game:started',started);socket.disconnect();}},[socket]);
  const submit=async type=>{if(pending)return;setPending(true);setError('');const result=await call(socket,type==='create'?'room:create':'room:join',{...identity,code});setPending(false);if(!result?.ok)return setError(result?.error||'Unable to connect.');setSelf({playerId:result.playerId,sessionToken:result.sessionToken});setRoom(result.room);setNotice(result.colorChanged?'That color was taken, so another available color was assigned.':'');setView('lobby');};
  const leave=async()=>{await call(socket,'room:leave',{});setRoom(null);setSelf(null);setView('menu');}; const me=room?.players?.find(player=>player.id===self?.playerId),isHost=Boolean(me&&room&&me.id===room.hostId),canStart=Boolean(isHost&&room?.players?.length>=2&&room.players.every(player=>player.id===room.hostId||player.ready));
  const updateSettings=patch=>call(socket,'room:settings',{...room.settings,boardPresetId:room.boardPresetId,...patch}).then(result=>!result.ok&&setError(result.error));
  if(view==='menu')return <section className="online-screen"><div className="online-card"><button className="text-back" onClick={onBack}>← Back</button><div className="eyebrow">Private rooms</div><h1>Online multiplayer</h1><p className={`connection-state ${connection}`}>● {connection}</p><div className="online-menu-actions"><button className="primary-button" onClick={()=>setView('create')}>Create room</button><button className="secondary-button" onClick={()=>setView('join')}>Join room</button></div></div></section>;
  if(view==='create'||view==='join')return <section className="online-screen"><form className="online-card" onSubmit={event=>{event.preventDefault();submit(view)}}><button type="button" className="text-back" onClick={()=>setView('menu')}>← Back</button><div className="eyebrow">{view==='create'?'Host a match':'Enter a room'}</div><h1>{view==='create'?'Create room':'Join room'}</h1><p className={`connection-state ${connection}`}>● {connection}</p>{view==='join'&&<label>Room code<input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} maxLength="6" required/></label>}<label>Player name<input value={identity.name} onChange={event=>setIdentity({...identity,name:event.target.value})} maxLength="18" required/></label><label>Avatar<div className="avatar-chooser"><select value={TOKEN_ICONS.includes(identity.icon)?identity.icon:''} onChange={event=>event.target.value&&setIdentity({...identity,icon:event.target.value})}><option value="">Custom</option>{TOKEN_ICONS.map(icon=><option key={icon}>{icon}</option>)}</select><input aria-label="Custom emoji avatar" title="Paste one emoji" value={TOKEN_ICONS.includes(identity.icon)?'':identity.icon} onChange={event=>setIdentity({...identity,icon:Array.from(event.target.value).slice(0,2).join('')})} placeholder="Paste emoji" maxLength="4"/></div></label><label>Player color<div className="online-colors">{COLORS.map(color=><button type="button" aria-label={color} className={identity.color===color?'selected':''} style={{background:color}} onClick={()=>setIdentity({...identity,color})} key={color}/>)}</div></label>{error&&<p className="online-error">{error}</p>}<button className="primary-button" type="submit" disabled={pending||connection!=='connected'}>{pending?'Connecting…':connection!=='connected'?'Waiting for server…':view==='create'?'Create room':'Join game'}</button></form></section>;
  if((view==='lobby'||view==='game')&&!room)return <section className="online-screen"><div className="online-card"><div className="eyebrow">Connecting</div><h1>Loading room…</h1><p>Waiting for the authoritative room snapshot.</p><button className="secondary-button" onClick={()=>setView('menu')}>Back</button></div></section>;
  if(view==='game')return <OnlineGame socket={socket} room={room} self={self} onSnapshot={setRoom} onLeave={leave}/>;
  return <section className="online-screen"><div className="online-lobby"><header><div><span className="eyebrow">Online room</span><h1>{room.code}</h1></div><button type="button" onClick={()=>navigator.clipboard?.writeText(room.code)}>Copy code</button><span className={`connection-state ${connection}`}>● {connection}</span></header>{notice&&<p className="online-notice">{notice}</p>}<div className="lobby-grid"><div className="lobby-players"><h2>Players {room.players.length} / 8</h2>{room.players.map((player,index)=><div className="lobby-player" key={player.id}><span className="lobby-avatar" style={{background:player.color}}>{player.icon}</span><div><b>{player.name}</b><small>P{index+1}{player.id===me?.id?' · YOU':''}</small></div><span>{player.id===room.hostId?'👑 HOST':player.ready?'✅ READY':'⏳ NOT READY'}</span><i title={player.connected?'Connected':'Reconnecting'}>{player.connected?'🟢':'🟡'}</i></div>)}{!isHost&&<button className="primary-button" onClick={()=>call(socket,'room:ready',{ready:!me.ready})}>{me?.ready?'Not ready':'Ready'}</button>}</div><div className="lobby-settings"><h2>Match settings</h2><label>Game mode<select disabled={!isHost} value={room.settings.mode} onChange={event=>updateSettings({mode:event.target.value})}>{Object.values(MODE_PRESETS).map(mode=><option value={mode.id} key={mode.id}>{mode.name}</option>)}</select></label><label>Board<select disabled={!isHost} value={room.boardPresetId} onChange={event=>updateSettings({boardPresetId:event.target.value})}>{Object.values(BOARD_PRESETS).map(board=><option value={board.id} key={board.id}>{board.icon} {board.name}</option>)}</select></label><label>Animation<select disabled={!isHost} value={room.settings.animationSpeed} onChange={event=>updateSettings({animationSpeed:event.target.value})}><option>fast</option><option>normal</option><option>cinematic</option></select></label><button className={`setting-toggle ${room.settings.exactRoll?'on':''}`} disabled={!isHost} onClick={()=>updateSettings({exactRoll:!room.settings.exactRoll})}><span>Exact roll</span><b>{room.settings.exactRoll?'ON':'OFF'}</b></button><button className={`setting-toggle ${room.settings.extraTurnOnSix?'on':''}`} disabled={!isHost} onClick={()=>updateSettings({extraTurnOnSix:!room.settings.extraTurnOnSix})}><span>Six = extra turn</span><b>{room.settings.extraTurnOnSix?'ON':'OFF'}</b></button>{error&&<p className="online-error">{error}</p>}{isHost&&<button className="primary-button" disabled={!canStart} onClick={async()=>{const result=await call(socket,'room:start',{});if(!result.ok)setError(result.error)}}>Start game</button>}<button className="secondary-button lobby-leave" onClick={leave}>Leave room</button></div></div>{import.meta.env.DEV&&<details className="multiplayer-debug"><summary>Multiplayer debug</summary><code>Server: {MULTIPLAYER_SERVER_URL}<br/>Socket: {socket.id}<br/>Player: {self?.playerId}<br/>Sequence: {room.eventSequence}<br/>Status: {room.status}</code></details>}</div></section>;
}
