import { COLORS } from '../gameEngine.js';
import { MODE_PRESETS, TOKEN_ICONS } from '../gameConfig.js';
import { BOARD_PRESETS, getSpecialTileCounts, SPECIAL_TILE_TYPES } from '../boardPresets.js';
import BoardConnections from './BoardConnections.jsx';
const Select = ({ label, value, onChange, options }) => <label className="setting-field"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option value={option.value ?? option} key={option.value ?? option}>{option.label ?? option}</option>)}</select></label>;
const Toggle = ({ label, value, onChange }) => <button type="button" className={`setting-toggle ${value ? 'on' : ''}`} onClick={() => onChange(!value)}><span>{label}</span><b>{value ? 'ON' : 'OFF'}</b></button>;
function BoardPreview({ board }) { return <div className="board-mini" aria-hidden="true">{Array.from({length:100},(_,i)=>100-i).map(tile=><i className={board.specialTiles[tile]?`mini-special ${board.specialTiles[tile]}`:''} key={tile}>{board.specialTiles[tile]&&SPECIAL_TILE_TYPES[board.specialTiles[tile]].icon}</i>)}<BoardConnections ladders={board.ladders} snakes={board.snakes}/></div>; }
export default function SetupScreen({ profiles, setProfiles, mode, setMode, settings, setSettings, boardPresetId, setBoardPresetId, onStart }) {
  const resize = next => setProfiles(current => Array.from({ length: Math.max(2, Math.min(8, next)) }, (_, i) => current[i] || { name: '', color: COLORS[i], icon: TOKEN_ICONS[i], isBot: false, difficulty: 'normal' }));
  const update = (index, patch) => setProfiles(current => current.map((profile, i) => i === index ? { ...profile, ...patch } : profile));
  const chooseMode = id => { setMode(id); if (id !== 'custom') setSettings({ ...MODE_PRESETS[id] }); };
  return <section className="setup-screen phase3-setup"><div className="setup-card"><div className="eyebrow">Configure your party</div><h1>Snakes <span>&</span> Ladders</h1><p className="subtitle">Choose the rules. Build your rivalry. Race to the top.</p><div className="mode-grid">{Object.values(MODE_PRESETS).map(item => <button type="button" className={`mode-card ${mode === item.id ? 'selected' : ''}`} key={item.id} onClick={() => chooseMode(item.id)}><strong>{item.name}</strong><small>{item.description}</small></button>)}<button type="button" className={`mode-card ${mode === 'custom' ? 'selected' : ''}`} onClick={() => chooseMode('custom')}><strong>⚙️ Custom</strong><small>Build your own rules.</small></button></div>
    {mode === 'custom' && <div className="custom-settings"><Toggle label="Exact roll to win" value={settings.exactRoll} onChange={value => setSettings({ ...settings, exactRoll: value })}/><Toggle label="Roll 6 = extra turn" value={settings.extraTurnOnSix} onChange={value => setSettings({ ...settings, extraTurnOnSix: value })}/><Toggle label="Wheel of Fate" value={settings.wheelEnabled} onChange={value => setSettings({ ...settings, wheelEnabled: value })}/><Toggle label="Chaos events" value={settings.chaosEnabled} onChange={value => setSettings({ ...settings, chaosEnabled: value })}/><Select label="Roulette frequency" value={settings.rouletteFrequency} onChange={value => setSettings({ ...settings, rouletteFrequency: value })} options={['low','normal','high']}/><Select label="Inventory limit" value={settings.inventoryLimit} onChange={value => setSettings({ ...settings, inventoryLimit: Number(value) })} options={[0,1,2,3]}/></div>}
    <div className="board-picker-heading"><div><label>Choose your board</label><p>Hand-designed layouts · independent from game mode</p></div><button type="button" onClick={()=>{const ids=Object.keys(BOARD_PRESETS);setBoardPresetId(ids[Math.floor(Math.random()*ids.length)]);}}>🎲 Surprise me</button></div><div className="board-preset-grid">{Object.values(BOARD_PRESETS).map(board=>{const counts=getSpecialTileCounts(board);return <button type="button" className={`board-preset-card ${boardPresetId===board.id?'selected':''}`} onClick={()=>setBoardPresetId(board.id)} key={board.id}><BoardPreview board={board}/><div className="board-preset-copy"><span className="board-style">{board.style}</span><strong>{board.icon} {board.name}</strong><small>{board.description}</small><div className="board-counts"><span>🐍 {Object.keys(board.snakes).length}</span><span>🪜 {Object.keys(board.ladders).length}</span><span>✨ {Object.values(counts).reduce((a,b)=>a+b,0)}</span></div><em>Recommended: {board.recommendedMode}</em></div></button>})}</div>
    <div className="setup-divider"/><div className="setup-toolbar"><div><label>Players</label><p>Human or local bot</p></div><div className="stepper"><button type="button" onClick={() => resize(profiles.length - 1)}>−</button><span>{profiles.length}</span><button type="button" onClick={() => resize(profiles.length + 1)}>+</button></div></div>
    <div className="player-inputs profile-inputs">{profiles.map((profile, i) => <div className="player-profile" key={i} style={{ '--player': profile.color }}><select className="icon-select" aria-label={`Player ${i + 1} token`} value={profile.icon} onChange={event => update(i, { icon: event.target.value })}>{TOKEN_ICONS.map(icon => <option key={icon}>{icon}</option>)}</select><input maxLength="18" aria-label={`Player ${i + 1} name`} placeholder={`Player ${i + 1}`} value={profile.name} onChange={event => update(i, { name: event.target.value })}/><input className="color-input" type="color" aria-label={`Player ${i + 1} color`} value={profile.color} onChange={event => update(i, { color: event.target.value })}/><button type="button" className={`bot-toggle ${profile.isBot ? 'active' : ''}`} onClick={() => update(i, { isBot: !profile.isBot })}>{profile.isBot ? 'BOT' : 'HUMAN'}</button>{profile.isBot && <select className="difficulty" value={profile.difficulty} onChange={event => update(i, { difficulty: event.target.value })}><option value="easy">Easy</option><option value="normal">Normal</option><option value="smart">Smart</option></select>}</div>)}</div>
    <button className="primary-button" type="button" onClick={onStart}>Start the race <span>→</span></button><p className="setup-note">2–8 players · Humans and bots · Local play</p></div><div className="setup-art" aria-hidden="true"><div className="art-grid"/><div className="art-number n100">100</div><div className="art-number n64">64</div><div className="art-ladder"><i/><i/><b/><b/><b/><b/></div><div className="art-snake"><span/></div><div className="art-copy">Every roll<br/><em>writes a story.</em></div></div></section>;
}
