import { useEffect, useState } from 'react';
import GameIcon from './GameIcon.jsx';
const COLORS = { power: '#32a879', attack: '#d95645', defense: '#3979c6', penalty: '#e79a39', chaos: '#8d5bc1' };
const LABELS = { fate: ['Chance changes everything', 'Wheel of Fate'], fortune: ['Good fortune awaits', 'Fortune Wheel'], battle: ['Challenge your rivals', 'Battle Wheel'], chaos: ['Anything can happen', 'Chaos Wheel'] };
export default function WheelOfFate({ player, effects, wheelType = 'fate', chooseEffect, onComplete, onNewGame, duration = 2400, autoSpin = false }) {
  const [spinning, setSpinning] = useState(false); const [result, setResult] = useState(null); const [rotation, setRotation] = useState(0); const segment = 360 / effects.length;
  const spin = () => { if (spinning || result) return; const selected = chooseEffect(); const index = effects.findIndex(effect => effect.id === selected.id); const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches; setSpinning(true); setRotation(1440 + 360 - index * segment - segment / 2); window.setTimeout(() => { setSpinning(false); setResult(selected); }, reduced ? 80 : duration); };
  useEffect(() => { if (autoSpin) { const timer = window.setTimeout(spin, 350); return () => window.clearTimeout(timer); } }, []);
  useEffect(() => { if (autoSpin && result) { const timer = window.setTimeout(() => onComplete(result), 500); return () => window.clearTimeout(timer); } }, [autoSpin, onComplete, result]);
  const [eyebrow, title] = LABELS[wheelType] || LABELS.fate; const gradient = `conic-gradient(${effects.map((effect, i) => `${COLORS[effect.category]} ${i * segment}deg ${(i + 1) * segment}deg`).join(',')})`;
  return <div className="phase-modal" role="dialog" aria-modal="true" aria-labelledby="wheel-title"><div className="wheel-card"><button className="modal-exit" type="button" onClick={onNewGame} disabled={spinning}>New game</button><div className="eyebrow">{eyebrow}</div><h2 id="wheel-title">{title}</h2><p className="wheel-player"><span style={{ background: player.color }}>{player.icon}</span>{player.name}, spin the wheel.</p><div className="wheel-stage"><div className="wheel-pointer">▼</div><div className="fate-wheel" style={{ background: gradient, transform: `rotate(${rotation}deg)`, transitionDuration: spinning ? `${duration}ms` : '0s' }}>{effects.map((effect, i) => <span key={effect.id} title={`${effect.name} · ${effect.rarity}`} style={{ transform: `rotate(${i * segment + segment / 2}deg)` }}><b>{effect.icon}</b></span>)}</div><div className="wheel-hub">{wheelType.toUpperCase()}</div></div>{result ? <div className={`roulette-result ${result.category} ${result.rarity}`}><GameIcon icon={result.icon} label={result.name} size="hero" category={result.category}/><div><small>{result.rarity} · {result.category}</small><strong>{result.name}</strong><p>{result.description}</p></div></div> : <div className="category-key">{Object.entries(COLORS).map(([name, color]) => <span key={name}><i style={{ background: color }}/>{name}</span>)}</div>}{!result ? <button className="primary-button wheel-action" type="button" onClick={spin} disabled={spinning}>{spinning ? 'The wheel is spinning…' : autoSpin ? `${player.name} is spinning…` : 'Spin the wheel'}</button> : <button className="primary-button wheel-action" type="button" onClick={() => onComplete(result)}>Continue</button>}</div></div>;
}
